lib/bookstore_web/router.ex
defmodule BookstoreWeb.Router do
  use BookstoreWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookstoreWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/authors", AuthorController
    resources "/books", BookController
  end

  # Other scopes may use custom stacks.
  # scope "/api", BookstoreWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BookstoreWeb.Telemetry
    end
  end
end

lib/bookstore/author.ex
defmodule Bookstore.Author do
  use Ecto.Schema
  import Ecto.Changeset
  import Ecto.Query, only: [from: 2]

  schema "authors" do
    field :email_address, :string
    field :name, :string

    timestamps()
  end

  @doc false
  def changeset(author , attrs \\ %{}) do
    author
    |> cast(attrs, [:name, :email_address])
    |> validate_required([:name, :email_address])
    |> unique_constraint(:email_address)
  end
end

lib/bookstore_web/controllers/author_controller.ex
defmodule BookstoreWeb.AuthorController do
  use BookstoreWeb, :controller
  import Ecto.Query, only: [from: 2]
  require Logger

  alias BookstoreWeb.Router
  alias Bookstore.Author
  alias Bookstore.Book
  alias Bookstore.Repo

  def index(conn, _params) do
    render(conn, "index.html", authors: Repo.all(Author))
  end

  def show(conn, %{"id" => id}) do
    books = Book
            |> Book.get_author_books(id)
            |> Repo.all

    Logger.debug "Var value: #{inspect(books)}"

    case Repo.get(Author, id) do
      author when is_map(author) ->
        render conn
        |> assign(:books, books)
        |> assign(:author, author)
        |> render("show.html")
      _ ->
        redirect conn, to: Router.Helpers.page_path(conn, :show, "unauthorized")
    end
  end

  def new(conn, _params) do
    changeset = Author.changeset(%Author{}, _params)
      conn
      |> assign(:changeset, changeset)
      |> render("new.html")
  end

  def create(conn, %{"author" => author_params}) do
    changeset = Author.changeset(%Author{}, author_params)
    case Repo.insert(changeset) do
      {:ok, _author} ->
        conn
        |> put_flash(:info, "Author created successfully.")
        |> redirect(to: Routes.author_path(conn, :index))
      {:error, changeset} ->
        conn
        |> assign(:changeset, changeset)
        |> render("new.html")
    end
  end

  def edit(conn, %{"id" => id}) do
    author = Repo.get!(Author, id)
    changeset = Author.changeset(author)
      conn
      |> assign(:changeset, changeset)
      |> assign(:author, author)
      |> render("edit.html")
  end

  def update(conn, %{"id" => id, "author" => author_params}) do
    author = Repo.get!(Author, id)
    changeset = Author.changeset(author, author_params)

    case Repo.update(changeset) do
      {:ok, author} ->
        conn
        |> put_flash(:info, "Author updated successfully.")
        |> redirect(to: Routes.author_path(conn, :show, author))
      {:error, changeset} ->
        conn
        |> assign(:changeset, changeset)
        |> assign(:author, author)
        |> render("edit.html")
    end
  end

  def delete(conn, %{"id" => id}) do
    author = Repo.get!(Author, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(author)

    conn
    |> put_flash(:info, "Author deleted successfully.")
    |> redirect(to: Routes.author_path(conn, :index))
  end
end

lib/bookstore_web/views/author_view.ex
defmodule BookstoreWeb.AuthorView do
  use BookstoreWeb, :view
end

lib/bookstore_web/templates/author/edit.html.eex
<h2>Edit author</h2>

<%= render "form.html", changeset: @changeset,
                        action: Routes.author_path(@conn, :update, @author) %>

<%= link "Back", to: Routes.author_path(@conn, :index) %>

lib/bookstore_web/templates/author/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email_address, class: "control-label" %>
    <%= text_input f, :email_address, class: "form-control" %>
    <%= error_tag f, :email_address %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/bookstore_web/templates/author/index.html.eex
<h2>Listing authors</h2>

<%= link "New author", to: Routes.author_path(@conn, :new) %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for author <- @authors do %>
    <tr>
      <td><%= author.name %></td>
      <td><%= author.email_address %></td>

      <td class="text-right">
        <%= link "Show", to: Routes.author_path(@conn, :show, author), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: Routes.author_path(@conn, :edit, author), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: Routes.author_path(@conn, :delete, author), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/bookstore_web/templates/author/new.html.eex
  
<h2>New author</h2>

<%= render "form.html", changeset: @changeset,
                        action: Routes.author_path(@conn, :create) %>

<%= link "Back", to: Routes.author_path(@conn, :index) %>

lib/bookstore_web/templates/author/show.html.eex
<h2>Show Author</h2>

<ul>

  <li>
    <strong>Author name:</strong>
    <%= @author.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @author.email_address %>
  </li>

</ul>

<h3>Author's book list</h3>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Isbn</th>
      <th>Action</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for book <- @books do %>
    <tr>
      <td><%= book.title %></td>
      <td><%= book.isbn %></td>

      <td class="text-right">
        <%= link "Show", to: Routes.book_path(@conn, :show, book), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: Routes.book_path(@conn, :edit, book), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: Routes.book_path(@conn, :delete, book), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "Back", to: Routes.author_path(@conn, :index) %>